Cms/Areas/Admin/Controllers/ContentController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Cms.Controllers;
using Cms.Core.Service;
using Cms.DataAccess.Entities;

namespace Cms.Areas.Admin.Controllers
{
    [Authorize]
    public class ContentController : BaseController
    {
        private readonly IContentItemService _contentService;
        
        public ContentController(IContentItemService contentService, IImageService imageService) : base (imageService)
        {
            _contentService = contentService;
        }
        public async Task<ActionResult> Start()
        {
            var model = await _contentService.GetPageItems("start");
            return View(model.Obj);
        }

        [HttpPost]
        public async Task<ActionResult> Start(ContentItem item)
        {
            item = SavePhoto(item);
            await _contentService.UpdateItem(item);
            return RedirectToAction("Start");
        }

        public async Task<ActionResult> Programs()
        {
            var model = await _contentService.GetPageItems("programs");
            return View(model.Obj);
        }

        [HttpPost]
        public async Task<ActionResult> Programs(ContentItem item)
        {
            item = SavePhoto(item);
            await _contentService.UpdateItem(item);
            return RedirectToAction("Programs");
        }
    }
}

Cms/Areas/Admin/Views/Content/Programs.cshtml
@using Cms.Common.Definition
@model Dictionary<string, List<Cms.DataAccess.Entities.ContentItem>>
@{
    ViewBag.Title = "Programs";
}
<h2>Programs page</h2>
<br />
<div class="row">
    <div class="col-sm-4">
        <ul class="nav nav-pills nav-stacked">
            @foreach (var location in Model.Keys)
            {
                <li class="@(Model.Keys.First() == location ? "active" : "")">
                    <a data-toggle="pill" href="#@location">@location.ToUpper().Replace("_", " ")</a>
                </li>
            }
        </ul>
    </div>
    <div class="col-sm-8">
        <div class="tab-content">
            @foreach (var location in Model.Keys)
            {
                <div id="@location" class="tab-pane fade@(Model.Keys.First() == location ? " in active" : "")">
                    @foreach (var item in Model[location])
                    {
                        using (Html.BeginForm("Programs", "Content", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                <h4>@location.Replace("_", " ") Item</h4>
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => item.Id)
                                @Html.HiddenFor(model => item.LocationId)
                                @if (!string.IsNullOrEmpty(item.ImageUrl))
                                {
                                    <div class="img-container col-md-offset-2">
                                        <img src="/Images/@item.ImageUrl" />
                                    </div>
                                }
                                <div class="form-group">
                                    <label class="control-label col-md-2">Image</label>
                                    <div class="col-md-10">
                                        <input type="file" class="form-control" name="Image" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => item.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => item.Title, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => item.Title, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => item.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => item.Description, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => item.Description, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => item.LinkUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => item.LinkUrl, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => item.LinkUrl, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Save" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        }
                    }
                </div>
            }
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cms/Areas/Admin/Views/Content/Start.cshtml
@using Cms.Common.Definition
@model Dictionary<string, List<Cms.DataAccess.Entities.ContentItem>>

@{
    ViewBag.Title = "Start";
}

<h2>Home page</h2>
<br/>
<div class="row">
    <div class="col-sm-4">
        <ul class="nav nav-pills nav-stacked">
            @foreach (var location in Model.Keys)
            {
                <li class="@(Model.Keys.First() == location ? "active" : "")">
                    <a data-toggle="pill" href="#@location">@location.ToUpper().Replace("_", " ")</a>
                </li>
            }
        </ul>
    </div>
    <div class="col-sm-8">
        <div class="tab-content">
            @foreach (var location in Model.Keys)
            {
                <div id="@location" class="tab-pane fade@(Model.Keys.First() == location ? " in active" : "")">
                    @foreach (var item in Model[location])
                    {
                        using (Html.BeginForm("Start", "Content", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                <h4>@location.Replace("_", " ") Item</h4>
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => item.Id)
                                @Html.HiddenFor(model => item.LocationId)
                                @if (!string.IsNullOrEmpty(item.ImageUrl))
                                {
                                    <div class="img-container col-md-offset-2">
                                        <img src="/Images/@item.ImageUrl" />
                                    </div>
                                }
                                <div class="form-group">
                                    <label class="control-label col-md-2">Image</label>
                                    <div class="col-md-10">
                                        <input type="file" class="form-control" name="Image" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => item.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => item.Title, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => item.Title, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => item.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => item.Description, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => item.Description, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => item.LinkUrl, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => item.LinkUrl, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => item.LinkUrl, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Save" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        }
                    }
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}