Cms/Areas/Admin/Controllers/DashboardController.cs
using System.Web.Mvc;
using Cms.Controllers;
using Cms.Core.Service;

namespace Cms.Areas.Admin.Controllers
{
    public class DashboardController : BaseController
    {
        public DashboardController(IImageService imageService) : base(imageService)
        {
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

Cms/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Blog</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="header">
        <a href="/" class="logo"></a>
        <div class="social">
            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
            <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
            <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
            <a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a>
        </div>
        <div class="nav">
            @*<a href="#" class="orang-btn">Start a PTA</a>
            <a href="#" class="orang-btn">Join PTA</a>
            <a href="#" class="orang-btn">Language</a>*@
            
            @if (Request.IsAuthenticated)
            {
                using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                {

                    @Html.AntiForgeryToken()
                    @Html.ActionLink("Profile", "Index", "Manage", routeValues: null, htmlAttributes: new { @class = "orang-btn" })
                    <span>&nbsp;</span>
                    <a href="javascript:document.getElementById('logoutForm').submit()" class="orang-btn">Log off</a>
                    @Html.ActionLink("Admin", "Index", "Dashboard", routeValues: new { area = "Admin" }, htmlAttributes: new { @class = "orang-btn" })

                }
            }
            else
            {
                @Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink", @class = "orang-btn" })
                @Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "orang-btn" })
            }
            @*<a href="#"><i class="fa fa-search" aria-hidden="true"></i></a>
            <a href="#"><i class="fa fa-bars" aria-hidden="true"></i></a>*@
        </div>
        
    </div>
@RenderBody()
<div class="footer-bg">
    <div class="footer wp-small">
        <div class="quarter-col">
            <a href="#" class="logo2"></a>

            <div class="office">

                <div class="address">
                    408 West 11th Street<br />
                    Austin, Texas 78701<br />
                    <br />
                    PHONE: 800-TALK-PTA (825-5782)<br />
                    EMAIL: <a href="mailto:TXPTA@TXPTA.ORG">TXPTA@TXPTA.ORG</a><br />
                    <br />
                    <a href="#" style="color:#e2851b;">VISIT OUR ONLINE MARKET</a>

                </div>
            </div>
        </div>
        <div class="half-col">
            <div class="title">
                Learn more
                <hr />
            </div>
            <div>
                <ul class="lll">
                    <li>
                        &raquo; <a href="#">Our story</a>
                    </li>
                    <li>
                        &raquo; <a href="#">Board of Directors</a>
                    </li>
                    <li>
                        &raquo; <a href="#">Mission and Vision</a>
                    </li>
                    <li>
                        &raquo; <a href="#">State Office Support</a>
                    </li>
                    <li>
                        &raquo; <a href="#">Newsroom</a>
                    </li>
                    <li>
                        &raquo; <a href="#">Statewide Partners</a>
                    </li>
                    <li>
                        &raquo; <a href="#">Annual Reports</a>
                    </li>
                    <li>
                        &raquo; <a href="#">National PTA</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="quarter-col">
            <div class="title">
                Follow us on
                <hr />
            </div>
            <div>
                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a>
            </div>
            <a href="#" class="comm"></a>
        </div>

    </div>
</div>
<div class="footer-copy">
    &copy; 2016 Texas PTA - All Rights reserved
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/layoutJs")
@RenderSection("scripts", required: false)
</body>
</html>