Cms/Controllers/BlogController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using Cms.Core.Service;

namespace Cms.Controllers
{
    public class BlogController : Controller
    {
        private readonly IPageService _pageService;
        public BlogController(IPageService pageService)
        {
            _pageService = pageService;
        }
        public PartialViewResult Titles()
        {
            var result =  _pageService.GetTitles();
            return PartialView(result.Obj);
        }

        public async Task<ActionResult> Post(int id)
        {
            var result = await _pageService.GetPage(id);
            return View(result.Obj);
        }
    }
}

Cms/Views/Blog/Post.cshtml
@using Cms.Common.Definition
@model Cms.ViewModels.Page.PageViewModel
<div class="slider">
    <ul class="bxslider">
        <li>
            <div class="slide">
                <img src="/Images/@Model.Banner.ImageUrl" alt="@Model.Banner.Title" />
                <div class="slide-big-page">
                    @Model.Banner.Title
                </div>
                <div class="slide-small-page">
                    @Model.Banner.Description
                </div>
            </div>
        </li>
        <li>
        </li>
    </ul>
</div>
@*<div class="partner-bar">
    <h3>THANKS TO OUR PARTNERS FOR BACKING THE FUTURE WITH US</h3>
    @foreach (var item in Model[Constants.ProgramsPage.Partners])
    {
        <a href="@item.LinkUrl" title="@item.Title">
            <img class="partner" src="/Images/@item.ImageUrl">
        </a>
    }
</div>*@
<div class="wp-small">
    <div class="inner-nav-column">
        <div class="inner-nav">
            <ul>
                @foreach (var page in Model.ChildPages)
                {
                    <li><a href="@Url.Action("Post", "Blog", new { id = page.Id })">@page.Title</a></li>
                }
            </ul>
        </div>
    </div>
    <div class="page-content">
        @Html.Raw(Model.Body)
    </div>
</div>

Cms/Views/Blog/Titles.cshtml
@model IEnumerable<Cms.ViewModels.Page.TitleViewModel>
<ul class="nav navbar-nav">
    @if (Model != null)
    {
        foreach (var title in Model)
        {
            <li>@Html.ActionLink(title.Title, "Post", new { id = title.Id })</li>
        }
    }
</ul>